# Generated by Django 4.2.5 on 2023-10-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_unique_together_remove_module_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
