# Generated by Django 4.2.5 on 2023-10-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0005_alter_enrollment_unique_together'),
        ('modules', '0003_alter_module_slug'),
        ('lessons', '0003_alter_lesson_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enrollments.enrollment')),
                ('lessons', models.ManyToManyField(blank=True, to='lessons.lesson')),
                ('modules', models.ManyToManyField(blank=True, to='modules.module')),
            ],
        ),
    ]
