# Generated by Django 4.2.5 on 2023-10-07 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollments', '0004_rename_user_enrollment_student'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='enrollments.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
